export const uz = {
  brand: 'Medic AI',
  prototype: 'Tibbiy xizmatlar prototipi',
  disclaimerShort: 'Tibbiy maslahat emas.',
  disclaimerMedical: 'Bu tashxis emas. Belgilarni shifokor bilan muhokama qiling.',
  call103: 'Shoshilinch holatda 103 ga murojaat qiling.',

  hub: {
    title: 'Medic AI — interaktiv prototip',
    subtitle: 'Ilova va hamkor panellari',
    cards: {
      app: 'Foydalanuvchi ilovasi',
      pharmacy: 'Dorixona paneli',
      clinic: 'Klinika paneli',
      hospital: 'Shifoxona paneli',
      doctor: 'Shifokor paneli',
    },
    cardDescriptions: {
      app: 'Mobil ilova',
      pharmacy: 'Dorixona',
      clinic: 'Klinika',
      hospital: 'Shifoxona',
      doctor: 'Shifokor',
    },
    splitDemo: 'Split-view demo',
    scanQr: 'Telefonda ochish uchun QR-kod',
  },

  tabs: {
    home: 'Bosh',
    ai: 'AI',
    doctor: 'Shifokor',
    pharmacy: 'Dorixona',
    profile: 'Profil',
  },

  welcome: {
    slides: [
      { title: 'AI tekshiruv', text: 'Belgilar boʻyicha dastlabki yoʻnalish oling (demo).' },
      { title: 'Shifokor', text: 'Qabul va onlayn konsultatsiya (maket).' },
      { title: 'Dorixona', text: 'Dori qidiring va buyurtma bering.' },
    ],
    start: 'Boshlash',
    skip: 'Oʻtkazib yuborish',
    next: 'Keyingi',
  },

  home: {
    greeting: 'Salom, Demo Foydalanuvchi',
    aiCta: 'AI bilan tekshirish',
    aiCtaSub: 'Dastlabki baho — tashxis emas',
    quick: { doctor: 'Shifokor', pharmacy: 'Dorixona', clinic: 'Klinika', map: 'Xarita' },
    upcoming: 'Yaqin qabul',
    nearby: 'Yaqin atrofda',
    orders: 'Buyurtmalarim',
  },

  ai: {
    title: 'AI Diagnostika',
    greeting: 'Asosiy shikoyatingiz nima?',
    typing: 'Yozmoqda…',
    restart: 'Qaytadan boshlash',
    severity: 'Ogʻirlik',
    send: 'Yuborish',
    placeholder: 'Javobingizni yozing…',
    toResult: 'Natijani koʻrish',
  },

  aiResult: {
    title: 'Dastlabki baho',
    emergency: 'Shoshilinch',
    call103: '103 ga qoʻngʻiroq',
    directions: 'Ehtimoliy yoʻnalishlar',
    urgency: 'Shoshilinchlik',
    specialist: 'Tavsiya etilgan mutaxassis',
    selfCare: 'Oʻzini parvarish',
    doctors: 'Tavsiya etilgan shifokorlar',
    book: 'Qabulga yozilish',
    online: 'Onlayn konsultatsiya',
    pharmacy: 'Dorixona',
    urgencyLabels: { low: 'Past', medium: 'Oʻrta', high: 'Yuqori' },
  },

  doctors: {
    title: 'Shifokorlar',
    search: 'Qidiruv…',
    empty: 'Mos shifokor topilmadi.',
    sortRating: 'Reyting',
    sortPrice: 'Narx',
    sortDistance: 'Yaqinlik',
    onlineOnly: 'Faqat onlayn',
    experience: 'yil tajriba',
    from: 'dan',
    all: 'Hammasi',
    available: 'Qabul mavjud',
    reviews: 'sharh',
    save: 'Saqlash',
    saved: 'Saqlangan',
    noResults: 'Natija topilmadi.',
  },

  book: {
    title: 'Qabulga yozilish',
    type: 'Turi',
    offline: 'Oflayn',
    online: 'Onlayn',
    date: 'Sana',
    time: 'Vaqt',
    confirm: 'Tasdiqlash',
    success: 'Qabul band qilindi',
    code: 'Qabul kodi',
    toAppointments: 'Qabullarim',
  },

  appointments: {
    title: 'Qabullarim',
    upcoming: 'Kelgusi',
    past: 'Oʻtgan',
    cancel: 'Bekor qilish',
    reschedule: 'Koʻchirish',
    connect: 'Ulanish',
    online: 'Onlayn',
    offline: 'Oflayn',
    empty: 'Qabullar yoʻq',
    status: {
      pending: 'Kutilmoqda',
      confirmed: 'Tasdiqlangan',
      rejected: 'Rad etilgan',
      completed: 'Yakunlangan',
      cancelled: 'Bekor qilingan',
    },
  },

  pharmacy: {
    title: 'Dori qidirish',
    search: 'Dori nomi…',
    promoted: 'Reklama',
    inStock: 'Bor',
    outOfStock: 'Yoʻq',
    addCart: 'Savatga',
    distance: 'km',
    empty: 'Dori topilmadi.',
  },

  cart: {
    title: 'Savat',
    pickup: 'Olib ketish',
    delivery: 'Yetkazib berish',
    payCard: 'Karta (demo)',
    payCash: 'Naqd',
    placeOrder: 'Buyurtma berish',
    empty: 'Savat boʻsh',
    payment: 'Toʻlov',
    addressPlaceholder: 'Masalan: Yunusobod, 12-mavze, 5-uy',
    total: 'Jami',
  },

  order: {
    title: 'Buyurtma',
    eta: 'Yetib borish vaqti',
    courier: 'Kuryer',
    pickupCode: 'Olib ketish kodi',
    myOrders: 'Buyurtmalarim',
    logistics: 'Dorixona logistikasi',
    assignCourier: 'Kuryerga biriktir',
    markDelivered: 'Yetkazildi (POD)',
    retry: 'Qayta urinish (demo)',
    priorityExpress: 'Tezkor',
    priorityStandard: 'Oddiy',
    podNote: 'Yetkazildi · imzo qabul qilindi (demo)',
    address: 'Manzil',
    timeline: 'Buyurtma tarixi',
    delivery: 'Yetkazib berish',
    pickup: 'Olib ketish',
    pharmacy: 'Dorixona',
    customerPickup: 'Mijoz oldi (demo)',
    failed: 'Yetkazilmadi',
    noOrders: 'Hali buyurtma yoʻq',
    showPickupCode: 'Kassada shu kodni ko‘rsating',
    pickupQrLabel: 'Olib ketish QR-kodi',
    items: 'Mahsulotlar',
    total: 'Jami',
    todayNew: 'Bugun yangi',
    onTheWay: 'Yoʻlda',
    delivered: 'Yetkazilgan',
    deliveryMap: 'Yetkazish yoʻnalishi (demo)',
    pharmacyPoint: 'Dorixona',
    courierPoint: 'Kuryer',
    addressPoint: 'Manzil',
    orderDate: 'Buyurtma sanasi',
    callCourier: 'Qoʻngʻiroq qilish',
    selectCourier: 'Kuryerni tanlang',
    assign: 'Biriktirish',
    failedAction: 'Yetkazilmadi',
    systemMessage: 'Holat yangilandi',
    chatPlaceholder: 'Xabar yozing…',
    noCourier: 'Kuryer hali biriktirilmagan',
    minutes: 'daq',
    itemCount: 'mahsulot',
    currency: 'soʻm',
    openPharmacy: 'Dorixonani ochish',
    notFound: 'Buyurtma topilmadi',
    chatReply: 'Rahmat, tez orada javob beramiz (demo).',
    send: 'Yuborish',
    nextStatus: 'Keyingi holat',
    emptyColumn: 'Buyurtmalar yoʻq',
    noFailedOrders: 'Muvaffaqiyatsiz yetkazish yoʻq',
    failureReasons: {
      noAnswer: 'Mijoz bilan bogʻlanib boʻlmadi',
      unavailable: 'Mijoz manzilda yoʻq edi',
    },
    events: {
      accepted: 'Buyurtma qabul qilindi',
      preparing: 'Dorixona buyurtmani tayyorlamoqda',
      ready: 'Buyurtma topshirishga tayyor',
      outForDelivery: 'Buyurtma kuryerga topshirildi',
      delivered: 'Buyurtma mijozga topshirildi',
      failed: 'Yetkazib berish yakunlanmadi',
      cancelled: 'Buyurtma bekor qilindi',
      courierAssigned: 'Kuryer buyurtmaga biriktirildi',
      retry: 'Qayta yetkazish boshlandi',
    },
    status: {
      accepted: 'Qabul qilindi',
      preparing: 'Tayyorlanmoqda',
      ready: 'Tayyor',
      delivered: 'Yetkazildi',
      out_for_delivery: 'Yoʻlda',
      failed: 'Yetkazilmadi',
      cancelled: 'Bekor',
    },
    chat: 'Dorixona bilan chat',
  },

  consult: {
    title: 'Onlayn konsultatsiya',
    end: 'Yakunlash',
    summary: 'Xulosa',
    prescription: 'Retsept (demo)',
    orderPharmacy: 'Dorixonadan buyurtma qilish',
  },

  clinics: {
    title: 'Klinika va shifoxonalar',
    filterClinic: 'Klinika',
    filterHospital: 'Shifoxona',
    book: 'Qabulga yozilish',
    all: 'Hammasi',
    empty: 'Muassasalar topilmadi.',
  },

  map: {
    title: 'Xarita',
    all: 'Hammasi',
    filterClinic: 'Klinika',
    filterPharmacy: 'Dorixona',
    filterHospital: 'Shifoxona',
    mockNote: 'Stilizatsiya qilingan xarita (demo)',
  },

  profile: {
    title: 'Profil',
    history: 'AI tekshiruvlar tarixi',
    saved: 'Saqlangan shifokorlar',
    darkMode: 'Qorongʻi rejim',
    reset: 'Demoni tiklash',
    user: 'Demo Foydalanuvchi',
    empty: 'Hozircha yoʻq',
  },

  pro: {
    login: 'Pro panel',
    demoLogin: 'Demo bilan kirish',
    rolePharmacy: 'Dorixona',
    roleClinic: 'Klinika',
    roleHospital: 'Shifoxona',
    roleDoctor: 'Shifokor',
    desktopHint: 'Panelni kompyuterda ochish tavsiya etiladi (1024px+).',
    search: 'Qidiruv…',
  },

  demoPanel: {
    title: 'Demo panel',
    reset: 'Demoni tiklash',
    accelerator: 'Tezlashtirgich (8s)',
    role: 'Rol',
    jumpAi: 'AI ssenariy',
  },

  orderToast: 'Buyurtma holati yangilandi',
  appointmentToast: 'Qabul holati yangilandi',
} as const
